const data = {
  colsData: [
    {
      width: 120,
      prop: "deptName1",
      label: "一级部门",
      fixed: "left",
      classNameFuc: val => {
        return "abc" + val;
      }
    },
    {
      width: 120,
      prop: "deptName2",
      label: "二级部门",
      fixed: "left"
    },
    {
      width: 120,
      prop: "deptName3",
      label: "三级部门",
      fixed: "left"
    },
    {
      width: 120,
      prop: "cateName1",
      label: "一级品类",
      fixed: "left",
      formater: val => {
        return val + "<span>abc</span>";
      }
    },
    {
      width: 120,
      prop: "cateName2",
      label: "二级品类",
      fixed: "left"
    },
    {
      width: 120,
      prop: "paramTypeName",
      label: "类型",
      fixed: "left"
    },
    {
      width: 120,
      prop: "showDimensionName",
      label: "展示维度",
      fixed: "left"
    },
    {
      width: 120,
      prop: "2019-9",
      label: "2019-W9",
      align: "right",
      canHide: false,
      editable: true,
      render: (h, params) => {
        let { row, column } = params;
        let val = row[column.prop];

        debugger;
        return h("div", [h("label", val), h("span", "ok")]);
      }
    },
    {
      width: 120,
      prop: "2019-10",
      label: "2019-W10",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-11",
      label: "2019-W11",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-12",
      label: "2019-W12",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-13",
      label: "2019-W13",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-14",
      label: "2019-W14",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-15",
      label: "2019-W15",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-16",
      label: "2019-W16",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-17",
      label: "2019-W17",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-18",
      label: "2019-W18",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-19",
      label: "2019-W19",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-20",
      label: "2019-W20",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-21",
      label: "2019-W21",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-22",
      label: "2019-W22",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-23",
      label: "2019-W23",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-24",
      label: "2019-W24",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-25",
      label: "2019-W25",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-26",
      label: "2019-W26",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-27",
      label: "2019-W27",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-28",
      label: "2019-W28",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-29",
      label: "2019-W29",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-30",
      label: "2019-W30",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-31",
      label: "2019-W31",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-32",
      label: "2019-W32",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-33",
      label: "2019-W33",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-34",
      label: "2019-W34",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-35",
      label: "2019-W35",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-36",
      label: "2019-W36",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-37",
      label: "2019-W37",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-38",
      label: "2019-W38",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-39",
      label: "2019-W39",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-40",
      label: "2019-W40",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-41",
      label: "2019-W41",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-42",
      label: "2019-W42",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-43",
      label: "2019-W43",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-44",
      label: "2019-W44",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-45",
      label: "2019-W45",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-46",
      label: "2019-W46",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-47",
      label: "2019-W47",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-48",
      label: "2019-W48",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-49",
      label: "2019-W49",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-50",
      label: "2019-W50",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-51",
      label: "2019-W51",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2019-52",
      label: "2019-W52",
      align: "right",
      canHide: false
    },
    {
      width: 120,
      prop: "2020-1",
      label: "2020-W1",
      align: "right",
      canHide: false
    }
  ],
  rowsData: [
    {
      cateId1: 670,
      cateName1: "电脑、办公",
      cateId2: 686,
      cateName2: "外设产品",
      elementId: "in",
      elementName: "入库",
      showDimension: "CATE_ID_2",
      showDimensionName: "二级品类",
      resultType: "UNITS",
      standardFlag: "",
      dateDimension: "WEEK",
      deptId1: 2789,
      deptName1: "电脑数码事业部",
      deptId2: 2923,
      deptName2: "文仪及配件业务部",
      deptId3: 2938,
      deptName3: "KA文具部",
      paramType: "in",
      paramTypeName: "入库",
      rowKey: "2938-686-in",
      showDimensionEnum: "CATE_ID_2",
      rowId: "2938-686-in",
      "2019-9": {
        year: 2019,
        month: null,
        week: "1",
        dateDimension: "WEEK",
        editable: true,
        validator: (value, oldValue) => {
          alert(value);
          alert(oldValue);
          // 编辑单元格的值时，要用到的检验函数。如果通过检验，返回true；否则返回字符串来具体说明失败的原因。
          if (isNaN(value)) {
            return "不是数值";
          }
          return true;
        },
        defaultFlag: true,
        paramType: null,
        value: 101,
        columnKey: "2019-1",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 120
      },
      "2019-10": {
        year: 2019,
        month: null,
        week: "10",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-10",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-11": {
        year: 2019,
        month: null,
        week: "11",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-11",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-12": {
        year: 2019,
        month: null,
        week: "12",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 9967,
        columnKey: "2019-12",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 9967
      },
      "2019-13": {
        year: 2019,
        month: null,
        week: "13",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-13",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-14": {
        year: 2019,
        month: null,
        week: "14",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-14",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-15": {
        year: 2019,
        month: null,
        week: "15",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-15",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-16": {
        year: 2019,
        month: null,
        week: "16",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: false,
        paramType: null,
        value: 737776,
        columnKey: "2019-16",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 737776
      },
      "2019-17": {
        year: 2019,
        month: null,
        week: "17",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: false,
        paramType: null,
        value: 7370,
        columnKey: "2019-17",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 7370
      },
      "2019-18": {
        year: 2019,
        month: null,
        week: "18",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-18",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-19": {
        year: 2019,
        month: null,
        week: "19",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-19",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-20": {
        year: 2019,
        month: null,
        week: "20",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-20",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-21": {
        year: 2019,
        month: null,
        week: "21",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-21",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-22": {
        year: 2019,
        month: null,
        week: "22",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-22",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-23": {
        year: 2019,
        month: null,
        week: "23",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-23",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-24": {
        year: 2019,
        month: null,
        week: "24",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-24",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-25": {
        year: 2019,
        month: null,
        week: "25",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: false,
        paramType: null,
        value: 1998,
        columnKey: "2019-25",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 1998
      },
      "2019-26": {
        year: 2019,
        month: null,
        week: "26",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-26",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-27": {
        year: 2019,
        month: null,
        week: "27",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-27",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-28": {
        year: 2019,
        month: null,
        week: "28",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-28",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-29": {
        year: 2019,
        month: null,
        week: "29",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-29",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-30": {
        year: 2019,
        month: null,
        week: "30",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-30",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-31": {
        year: 2019,
        month: null,
        week: "31",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-31",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-32": {
        year: 2019,
        month: null,
        week: "32",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-32",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-33": {
        year: 2019,
        month: null,
        week: "33",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-33",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-34": {
        year: 2019,
        month: null,
        week: "34",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-34",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-35": {
        year: 2019,
        month: null,
        week: "35",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-35",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-36": {
        year: 2019,
        month: null,
        week: "36",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-36",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-37": {
        year: 2019,
        month: null,
        week: "37",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-37",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-38": {
        year: 2019,
        month: null,
        week: "38",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-38",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-39": {
        year: 2019,
        month: null,
        week: "39",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-39",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-40": {
        year: 2019,
        month: null,
        week: "40",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-40",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-41": {
        year: 2019,
        month: null,
        week: "41",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-41",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-42": {
        year: 2019,
        month: null,
        week: "42",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-42",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-43": {
        year: 2019,
        month: null,
        week: "43",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-43",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-44": {
        year: 2019,
        month: null,
        week: "44",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-44",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-45": {
        year: 2019,
        month: null,
        week: "45",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-45",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-46": {
        year: 2019,
        month: null,
        week: "46",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-46",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-47": {
        year: 2019,
        month: null,
        week: "47",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-47",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-48": {
        year: 2019,
        month: null,
        week: "48",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-48",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-49": {
        year: 2019,
        month: null,
        week: "49",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-49",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-50": {
        year: 2019,
        month: null,
        week: "50",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-50",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-51": {
        year: 2019,
        month: null,
        week: "51",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-51",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-52": {
        year: 2019,
        month: null,
        week: "52",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-52",
        columnName: null,
        rowKey: "2938-686-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      }
    },
    {
      cateId1: 670,
      cateName1: "电脑、办公",
      cateId2: 716,
      cateName2: "办公设备",
      elementId: "in",
      elementName: "入库",
      showDimension: "CATE_ID_2",
      showDimensionName: "二级品类",
      resultType: "UNITS",
      standardFlag: "",
      dateDimension: "WEEK",
      deptId1: 2789,
      deptName1: "电脑数码事业部",
      deptId2: 2923,
      deptName2: "文仪及配件业务部",
      deptId3: 2938,
      deptName3: "KA文具部",
      paramType: "in",
      paramTypeName: "入库",
      rowKey: "2938-716-in",
      showDimensionEnum: "CATE_ID_2",
      rowId: "2938-716-in",
      "2019-1": {
        year: 2019,
        month: null,
        week: "1",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-1",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-09": {
        year: 2019,
        month: null,
        week: "10",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-10",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 40
      },
      "2019-11": {
        year: 2019,
        month: null,
        week: "11",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-11",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-12": {
        year: 2019,
        month: null,
        week: "12",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 83596,
        columnKey: "2019-12",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 83596
      },
      "2019-13": {
        year: 2019,
        month: null,
        week: "13",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-13",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-14": {
        year: 2019,
        month: null,
        week: "14",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-14",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-15": {
        year: 2019,
        month: null,
        week: "15",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-15",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-16": {
        year: 2019,
        month: null,
        week: "16",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-16",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-17": {
        year: 2019,
        month: null,
        week: "17",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-17",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-18": {
        year: 2019,
        month: null,
        week: "18",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-18",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-19": {
        year: 2019,
        month: null,
        week: "19",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-19",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-20": {
        year: 2019,
        month: null,
        week: "20",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-20",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-21": {
        year: 2019,
        month: null,
        week: "21",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-21",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-22": {
        year: 2019,
        month: null,
        week: "22",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-22",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-23": {
        year: 2019,
        month: null,
        week: "23",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-23",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-24": {
        year: 2019,
        month: null,
        week: "24",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-24",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-25": {
        year: 2019,
        month: null,
        week: "25",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-25",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-26": {
        year: 2019,
        month: null,
        week: "26",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-26",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-27": {
        year: 2019,
        month: null,
        week: "27",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-27",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-28": {
        year: 2019,
        month: null,
        week: "28",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-28",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-29": {
        year: 2019,
        month: null,
        week: "29",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-29",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-30": {
        year: 2019,
        month: null,
        week: "30",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-30",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-31": {
        year: 2019,
        month: null,
        week: "31",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-31",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-32": {
        year: 2019,
        month: null,
        week: "32",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-32",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-33": {
        year: 2019,
        month: null,
        week: "33",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-33",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-34": {
        year: 2019,
        month: null,
        week: "34",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-34",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-35": {
        year: 2019,
        month: null,
        week: "35",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-35",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-36": {
        year: 2019,
        month: null,
        week: "36",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-36",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-37": {
        year: 2019,
        month: null,
        week: "37",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-37",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-38": {
        year: 2019,
        month: null,
        week: "38",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-38",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-39": {
        year: 2019,
        month: null,
        week: "39",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-39",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-40": {
        year: 2019,
        month: null,
        week: "40",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-40",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-41": {
        year: 2019,
        month: null,
        week: "41",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-41",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-42": {
        year: 2019,
        month: null,
        week: "42",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-42",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-43": {
        year: 2019,
        month: null,
        week: "43",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-43",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-44": {
        year: 2019,
        month: null,
        week: "44",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-44",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-45": {
        year: 2019,
        month: null,
        week: "45",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-45",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-46": {
        year: 2019,
        month: null,
        week: "46",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-46",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-47": {
        year: 2019,
        month: null,
        week: "47",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-47",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-48": {
        year: 2019,
        month: null,
        week: "48",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-48",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-49": {
        year: 2019,
        month: null,
        week: "49",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-49",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-50": {
        year: 2019,
        month: null,
        week: "50",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-50",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-51": {
        year: 2019,
        month: null,
        week: "51",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-51",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-52": {
        year: 2019,
        month: null,
        week: "52",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-52",
        columnName: null,
        rowKey: "2938-716-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      }
    },
    {
      cateId1: 670,
      cateName1: "电脑、办公",
      cateId2: 729,
      cateName2: "文具/耗材",
      elementId: "in",
      elementName: "入库",
      showDimension: "CATE_ID_2",
      showDimensionName: "二级品类",
      resultType: "UNITS",
      standardFlag: "",
      dateDimension: "WEEK",
      deptId1: 2789,
      deptName1: "电脑数码事业部",
      deptId2: 2923,
      deptName2: "文仪及配件业务部",
      deptId3: 2938,
      deptName3: "KA文具部",
      paramType: "in",
      paramTypeName: "入库",
      rowKey: "2938-729-in",
      showDimensionEnum: "CATE_ID_2",
      rowId: "2938-729-in",
      "2019-1": {
        year: 2019,
        month: null,
        week: "1",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-1",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-10": {
        year: 2019,
        month: null,
        week: "10",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-10",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-11": {
        year: 2019,
        month: null,
        week: "11",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-11",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-12": {
        year: 2019,
        month: null,
        week: "12",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 2069665,
        columnKey: "2019-12",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 2069665
      },
      "2019-13": {
        year: 2019,
        month: null,
        week: "13",
        dateDimension: "WEEK",
        editable: false,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-13",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-14": {
        year: 2019,
        month: null,
        week: "14",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-14",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-15": {
        year: 2019,
        month: null,
        week: "15",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-15",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-16": {
        year: 2019,
        month: null,
        week: "16",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-16",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-17": {
        year: 2019,
        month: null,
        week: "17",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-17",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-18": {
        year: 2019,
        month: null,
        week: "18",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-18",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-19": {
        year: 2019,
        month: null,
        week: "19",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-19",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-20": {
        year: 2019,
        month: null,
        week: "20",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-20",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-21": {
        year: 2019,
        month: null,
        week: "21",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-21",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-22": {
        year: 2019,
        month: null,
        week: "22",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-22",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-23": {
        year: 2019,
        month: null,
        week: "23",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-23",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-24": {
        year: 2019,
        month: null,
        week: "24",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-24",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-25": {
        year: 2019,
        month: null,
        week: "25",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-25",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-26": {
        year: 2019,
        month: null,
        week: "26",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-26",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-27": {
        year: 2019,
        month: null,
        week: "27",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-27",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-28": {
        year: 2019,
        month: null,
        week: "28",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-28",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-29": {
        year: 2019,
        month: null,
        week: "29",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-29",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-30": {
        year: 2019,
        month: null,
        week: "30",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-30",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-31": {
        year: 2019,
        month: null,
        week: "31",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-31",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-32": {
        year: 2019,
        month: null,
        week: "32",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-32",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-33": {
        year: 2019,
        month: null,
        week: "33",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-33",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-34": {
        year: 2019,
        month: null,
        week: "34",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-34",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-35": {
        year: 2019,
        month: null,
        week: "35",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-35",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-36": {
        year: 2019,
        month: null,
        week: "36",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-36",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-37": {
        year: 2019,
        month: null,
        week: "37",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-37",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-38": {
        year: 2019,
        month: null,
        week: "38",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-38",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-39": {
        year: 2019,
        month: null,
        week: "39",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-39",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-40": {
        year: 2019,
        month: null,
        week: "40",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-40",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-41": {
        year: 2019,
        month: null,
        week: "41",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-41",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-42": {
        year: 2019,
        month: null,
        week: "42",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-42",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-43": {
        year: 2019,
        month: null,
        week: "43",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-43",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-44": {
        year: 2019,
        month: null,
        week: "44",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-44",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-45": {
        year: 2019,
        month: null,
        week: "45",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-45",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-46": {
        year: 2019,
        month: null,
        week: "46",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-46",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-47": {
        year: 2019,
        month: null,
        week: "47",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-47",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-48": {
        year: 2019,
        month: null,
        week: "48",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-48",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-49": {
        year: 2019,
        month: null,
        week: "49",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-49",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-50": {
        year: 2019,
        month: null,
        week: "50",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-50",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-51": {
        year: 2019,
        month: null,
        week: "51",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-51",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      },
      "2019-52": {
        year: 2019,
        month: null,
        week: "52",
        dateDimension: "WEEK",
        editable: true,
        defaultFlag: true,
        paramType: null,
        value: 0,
        columnKey: "2019-52",
        columnName: null,
        rowKey: "2938-729-in",
        dimMap: {
          ShowDimensionEnum: "CATE_ID_2",
          DateDimensionEnum: "WEEK",
          ResultTypeDimensionEnum: "UNITS",
          HistoryValueTypeEnum: "PLAN",
          VersionTypeEnum: "NEWEST"
        },
        dateDimensionEnum: "WEEK",
        upHalfWeek: false,
        val: 0
      }
    }
  ]
};
export default data;
